### ISSUE TITLE
Play sound when button clicked

### ISSUE THREAD

**Issue by Nikoloutsos** [jimfilippou/hci-project#7]
Nice UI, but I think it would be awesome if you played a short sound for some of your buttons.

For example when user turn ON/OFF the air-conditioner you could play something from [here](https://www.soundsnap.com/tags/switch_off_0)

**Comment by jimfilippou** [comment]
Ευχαριστούμε για την ιδέα συνάδελφε @Nikoloutsos !!! Θα το υλοποιήσουμε!

**Comment by jimfilippou** [comment]
Fixed in the following commits 👇

- ad701d858f38e107feef8c8ad6bd76e1210ef841
- 2438e11d7304823748bb1fb5cf6c7bde241a92e1
- dd31a316234af7200b6bfb1d4a4aad3811178361

Thanks for the issue!
